# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: "Default"

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Prod Registry'
    repository: 'eshop/basket.api'
    command: 'buildAndPush'
    Dockerfile: 'src/Services/Basket/Basket.API/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest